# Adding a Logging file for the EDA

In [2]:
import logging
from datetime import datetime

logging.basicConfig(
    filename="Aadhaar_Enrollment_Equity_Assessment_execution.log",
    filemode="a",
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s"
)

logging.info("==============================================")
logging.info("EDA Phase-1 started")
logging.info(f"Notebook execution started at {datetime.now()}")

# Importing Data From MySQL

In [3]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine(
    "mysql+pymysql://root:PASSWORD%40629@localhost/uidai"
)
uidai = pd.read_sql(
    "SELECT * FROM uidai_district_enrollment_profile",
    con=engine
)

In [4]:
uidai.shape
uidai.head()

,state,district,total_enrolled,age_0_5,age_5_17,age_18_greater,child_ratio,youth_ratio,adult_ratio,dependency_ratio,ESI,dependency_status
0,Andaman & Nicobar Islands,Andamans,73,68,5,0,0.931507,0.068493,0.0,NaN,0.0,Undefined
1,Andaman & Nicobar Islands,Nicobars,1,1,0,0,1.000000,0.000000,0.0,NaN,0.0,Undefined
2,Andaman & Nicobar Islands,South Andaman,37,37,0,0,1.000000,0.000000,0.0,NaN,0.0,Undefined
3,Andaman and Nicobar Islands,Nicobar,74,63,11,0,0.851351,0.148649,0.0,NaN,0.0,Undefined
4,Andaman and Nicobar Islands,North And Middle Andaman,129,125,4,0,0.968992,0.031008,0.0,NaN,0.0,Undefined

# Which districts have structurally low Aadhaar enrollment maturity?
These districts need policy intervention, not cosmetic enrollment drives.

In [5]:
logging.info("Q1 started: Identifying structurally low enrollment maturity districts")

q1_low_maturity = uidai[
    (uidai["ESI"] < 0.45) &
    (uidai["dependency_ratio"] > 1.2) &
    (uidai["total_enrolled"] > 1000)
].sort_values("ESI")

q1_low_maturity[
    ["state", "district", "total_enrolled", "ESI", "dependency_ratio"]
].head(10)

logging.info("Q1 completed | districts_identified=%d", q1_low_maturity.shape[0])
display(q1_low_maturity.head(10))

,state,district,total_enrolled,age_0_5,age_5_17,age_18_greater,child_ratio,youth_ratio,adult_ratio,dependency_ratio,ESI,dependency_status
564,Maharashtra,Raigarh,5119,4318,800,1,0.843524,0.156281,0.000195,5118.0,0.000195,Defined
834,Tamil Nadu,Tirunelveli,9423,8080,1341,2,0.857476,0.142311,0.000212,4710.5,0.000212,Defined
20,Andhra Pradesh,Hyderabad,4708,3723,984,1,0.790782,0.209006,0.000212,4707.0,0.000212,Defined
182,Chhattisgarh,Janjgir-champa,4475,3918,556,1,0.875531,0.124246,0.000223,4474.0,0.000223,Defined
395,Karnataka,Bellary,4142,3556,585,1,0.858522,0.141236,0.000241,4141.0,0.000241,Defined
829,Tamil Nadu,Theni,3402,2851,550,1,0.838036,0.161670,0.000294,3401.0,0.000294,Defined
394,Karnataka,Belgaum,6637,5766,869,2,0.868766,0.130933,0.000301,3317.5,0.000301,Defined
294,Haryana,Sirsa,3190,2996,193,1,0.939185,0.060502,0.000313,3189.0,0.000313,Defined
15,Andhra Pradesh,Cuddapah,5762,5357,403,2,0.929712,0.069941,0.000347,2880.0,0.000347,Defined
36,Andhra Pradesh,Nellore,5264,4524,738,2,0.859422,0.140198,0.000380,2631.0,0.000380,Defined

# Which states show high intra-state inequality in Aadhaar maturity?
 This shows:
* The minimum ESI district
* The maximum ESI district
* The gap between the two shows the level of governance inequality

In [6]:
logging.info("Q2 started: Intra-state Aadhaar inequality with extreme districts")


uidai_esi = uidai.loc[uidai["ESI"].notna(), ["state", "district", "ESI"]]


esi_stats = (
    uidai_esi
    .groupby("state", as_index=False)
    .agg(
        districts=("district", "nunique"),
        min_ESI=("ESI", "min"),
        max_ESI=("ESI", "max")
    )
)


min_districts = (
    uidai_esi
    .loc[uidai_esi.groupby("state")["ESI"].idxmin()]
    .rename(columns={
        "district": "min_ESI_district",
        "ESI": "min_ESI"
    })
)


max_districts = (
    uidai_esi
    .loc[uidai_esi.groupby("state")["ESI"].idxmax()]
    .rename(columns={
        "district": "max_ESI_district",
        "ESI": "max_ESI"
    })
)


q2 = (
    esi_stats
    .merge(min_districts[["state", "min_ESI_district"]], on="state", how="left")
    .merge(max_districts[["state", "max_ESI_district"]], on="state", how="left")
)


q2["ESI_gap"] = q2["max_ESI"] - q2["min_ESI"]


display(
    q2.sort_values("ESI_gap", ascending=False).head(10)
)

logging.info("Q2 completed | states=%d", q2.shape[0])

,state,districts,min_ESI,max_ESI,min_ESI_district,max_ESI_district,ESI_gap
29,Meghalaya,14,0.000000,0.720049,Jaintia Hills,Eastern West Khasi Hills,0.720049
30,Mizoram,12,0.000000,0.647059,Hnahthial,Khawzawl,0.647059
39,Sikkim,10,0.000000,0.608696,North,Namchi,0.608696
3,Arunachal Pradesh,25,0.000000,0.333333,Dibang Valley,Leparada,0.333333
37,Punjab,28,0.000000,0.325727,Firozpur,Kapurthala,0.325727
50,West Bengal,58,0.000000,0.303571,Burdwan,Kalimpong,0.303571
26,Madhya Pradesh,61,0.000000,0.285714,Harda *,Pandhurna,0.285714
31,Nagaland,17,0.037572,0.310345,Phek,Tseminyu,0.272773
4,Assam,38,0.000000,0.269231,Tamulpur District,West Karbi Anglong,0.269231
27,Maharashtra,53,0.000000,0.232323,Ahilyanagar,Chhatrapati Sambhajinagar,0.232323

Meghalaya is the state with the largest ESI gap

# Which districts are child-heavy enrollment zones?
These districts indicate future UIDAI workload and school-linked identity needs.

Child-heavy districts:

child_ratio > 0.35

total_enrolled > 1000

In [7]:
from IPython.display import display, Markdown

logging.info("Q3 started: Identifying child-heavy enrollment districts")

q3_child_heavy = uidai.loc[
    (uidai["child_ratio"].notna()) &
    (uidai["child_ratio"] > 0.35) &
    (uidai["total_enrolled"] > 1000),
    ["state", "district", "child_ratio", "total_enrolled"]
].sort_values("child_ratio", ascending=False)

display(Markdown("### Top 10 Child-Heavy Districts Across India"))
display(q3_child_heavy.head(10))

q3_top_by_state = (
    q3_child_heavy
    .loc[q3_child_heavy.groupby("state")["child_ratio"].idxmax()]
    .sort_values("child_ratio", ascending=False)
)

display(Markdown("### Most Child-Heavy District in Each State"))
display(q3_top_by_state)

display(Markdown("### Complete List of Child-Heavy Districts"))
display(q3_child_heavy)

logging.info(
    "Q3 completed | districts_identified=%d | states_covered=%d",
    q3_child_heavy.shape[0],
    q3_top_by_state["state"].nunique()
)

### Top 10 Child-Heavy Districts Across India

                state      district  child_ratio  total_enrolled
300  Himachal Pradesh      Hamirpur     0.986195            1159
311  Himachal Pradesh           Una     0.982544            1203
307  Himachal Pradesh         Mandi     0.978243            2436
301  Himachal Pradesh        Kangra     0.975572            3848
282           Haryana          Jind     0.975470            3669
531       Maharashtra      Bhandara     0.967240            1862
45     Andhra Pradesh    Srikakulam     0.967193            4176
283           Haryana       Kaithal     0.966048            2857
296           Haryana  Yamuna Nagar     0.964319            3223
285           Haryana   Kurukshetra     0.963235            2312

### Most Child-Heavy District in Each State

                  state               district  child_ratio  total_enrolled
300    Himachal Pradesh               Hamirpur     0.986195            1159
282             Haryana                   Jind     0.975470            3669
531         Maharashtra               Bhandara     0.967240            1862
45       Andhra Pradesh             Srikakulam     0.967193            4176
166        Chhattisgarh                  Balod     0.956767            1596
427           Karnataka                 Mandya     0.945839            3545
493      Madhya Pradesh                 Mandla     0.945668            4859
812          Tamil Nadu            Kanyakumari     0.945473            1944
713         Pondicherry            Pondicherry     0.935754            1074
850           Telangana               Jagitial     0.932389            1553
343   Jammu and Kashmir                Pulwama     0.928258            1826
737              Punjab              Pathankot     0.925590            1102
654              Odisha             Jharsuguda     0.924512            1126
989         Uttarakhand                Chamoli     0.919617            1045
717          Puducherry             Puducherry     0.912281            1311
164          Chandigarh             Chandigarh     0.907146            2617
1052        West Bengal        Purba Medinipur     0.903939           14116
256             Gujarat                Narmada     0.900485            1236
458              Kerala                Wayanad     0.833885            1511
230                 Goa              North Goa     0.818939            1320
136               Bihar             Kishanganj     0.793074            8230
223               Delhi       North West Delhi     0.771305           15501
918       Uttar Pradesh                 Bijnor     0.765643           16445
768           Rajasthan             Ganganagar     0.762411            5358
377           Jharkhand                 Palamu     0.760743            8401
94                Assam                  Hojai     0.750432            6940
602             Mizoram                 Aizawl     0.732478            1013
897             Tripura           West Tripura     0.701863            2737
580             Manipur            Imphal West     0.520953            1217
597           Meghalaya  South West Garo Hills     0.487637            4934
624            Nagaland                  Peren     0.350793            1451

### Complete List of Child-Heavy Districts

                state         district  child_ratio  total_enrolled
300  Himachal Pradesh         Hamirpur     0.986195            1159
311  Himachal Pradesh              Una     0.982544            1203
307  Himachal Pradesh            Mandi     0.978243            2436
301  Himachal Pradesh           Kangra     0.975572            3848
282           Haryana             Jind     0.975470            3669
..                ...              ...          ...             ...
935     Uttar Pradesh        Gorakhpur     0.372097           19675
980     Uttar Pradesh  Siddharth Nagar     0.369270            4341
98              Assam    Karbi Anglong     0.357726            7967
979     Uttar Pradesh        Shrawasti     0.354109            5038
624          Nagaland            Peren     0.350793            1451

[667 rows x 4 columns]

<span style="font-size:15px; font-weight:bold;">
• Hamirpur is the most child-heavy district.
    
• Himachal Pradesh, Haryana and Maharashtra are the three most child-heavy states of India.

</span>

In [8]:
logging.info("Q4 started: Near-saturation Aadhaar districts")

q4 = uidai.loc[
    (uidai["ESI"].notna()) &
    (uidai["dependency_ratio"].notna()) &
    (uidai["ESI"] > 0.75) &
    (uidai["dependency_ratio"] < 0.6)
]

q4_count = q4.shape[0]

display(pd.DataFrame({"near_saturation_districts": [q4_count]}))

logging.info("Q4 completed | near_saturation_districts=%d", q4_count)

   near_saturation_districts
0                          0

<span style="font-size:15px; font-weight:bold;">
• India has not reached Aadhaar enrollment saturation in any state or district yet
    
• The number of states qualifying the criteria of ESI>0.75 and dependency_ratio<0.6 are zero.

• This indicates that Aadhaar enrollment remains a structurally continuous process, driven by India’s demographic depth rather than administrative lag.
</span>

# Number of districts in each maturity stage

In [10]:
import numpy as np
logging.info("Q5 started: Enrollment maturity classification")

uidai_q5 = uidai.copy()

uidai_q5["maturity_stage"] = np.select(
    [
        uidai_q5["ESI"] < 0.45,
        uidai_q5["ESI"].between(0.45, 0.65),
        uidai_q5["ESI"] > 0.65
    ],
    [
        "Emerging",
        "Transitional",
        "Mature"
    ],
    default="Unknown"
)

q5 = (
    uidai_q5["maturity_stage"]
    .value_counts()
    .rename_axis("Maturity Stage")
    .reset_index(name="Number of Districts")
)

display(q5)

logging.info("Q5 completed")

  Maturity Stage  Number of Districts
0       Emerging                 1065
1   Transitional                    3
2         Mature                    1

<span style="font-size:15px; font-weight:bold;">
This shows most of the districts in the country are from the emerging maturity stage where the ESI<0.45 that is less than 45% enrollments in the districts are adults.
</span>

# Districts with Administrative/Data Anomalies

In [11]:
logging.info("Q6 started: Administrative anomaly detection")

q6 = uidai.loc[
    (uidai["total_enrolled"] < 500) |
    (uidai["dependency_ratio"].isna()) |
    (uidai["ESI"].isna()),
    ["state", "district", "total_enrolled", "ESI", "dependency_ratio"]
]

display(q6.head(10))

logging.info("Q6 completed | rows=%d", q6.shape[0])

,state,district,total_enrolled,ESI,dependency_ratio
0,Andaman & Nicobar Islands,Andamans,73,0.000000,NaN
1,Andaman & Nicobar Islands,Nicobars,1,0.000000,NaN
2,Andaman & Nicobar Islands,South Andaman,37,0.000000,NaN
3,Andaman and Nicobar Islands,Nicobar,74,0.000000,NaN
4,Andaman and Nicobar Islands,North And Middle Andaman,129,0.000000,NaN
5,Andaman and Nicobar Islands,South Andaman,187,0.000000,NaN
9,Andhra Pradesh,Anantapur,4311,0.000000,NaN
10,Andhra Pradesh,Ananthapur,1937,0.000000,NaN
13,Andhra Pradesh,Bapatla,482,0.033195,29.125
21,Andhra Pradesh,K.V.Rangareddy,67,0.000000,NaN

<span style="font-size:15px; font-weight:bold;">
These are the districts which show unusual behaviour in their enrollment data not because of wrong data, but because of some unavoidable reasons.
    these can be:
    
    * Total enrollments<500 that depicts low Aadhaar activity
    * Those with dependency ratio NaN, not because of wrong data but because of zero adult enrollments
    * Those with ESI=0 representing zero adult enrollments.
</span>